### ISSUE TITLE
Offer mechanism to "group" and "re-order" the terms

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod-utils#14]
e.g. a YAML map like:

```
- category: "General concepts"
  terms: 
    - chain
    - agreement of common understanding
    - management information
- category: "EXPRESS concepts"
  terms:
    - annotated EXPRESS schema
    - type_of_product
```

And the output becomes:

```
=== General concepts

==== chain
...
==== agreement of common understanding
...


=== EXPRESS concepts

==== annotated EXPRESS schema
...

==== type_of_product
...
```
