### ISSUE TITLE
Annotated EXPRESS: Convert all schema history information into independent per-schema YAML files

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod-utils#146]
Inside `resource.xml` files there are EXPRESS schema changes (history of changes to the EXPRESS schemas included in that document).

The goal is to migrate these schema change information to the directory location of the schema themselves.

The EXPRESS schemas are located according to this file path pattern:
* `resources/{schema-name}/{schema-name}.exp`
* `modules/{schema-name}/{schema-name}.exp`

We want to create a new YAML file that contains the schema changes at:
* `resources/{schema-name}/{schema-name}.changes.yml`
* `modules/{schema-name}/{schema-name}.changes.yml`

This is an example from:
`data/resource_docs/geometric_and_topological_representation/resource.xml`

The document `geometric_and_topological_representation` includes several schemas, including `geometry_schema`.

* In the `<changes>` element, it contains multiple `<change_edition>` elements. Each element represents an editon of this document.
* In each `<change_edition>` element, it contains the changes of individual schemas (such as `geometry_schema`).
* We need to extract these schema changes "per schema" into the `{schema-name}/changes.yml` file

```xml
<changes>
   <change_edition version="2">
      <description>
         Also changes of technical corrigendum 1 of edition 2 are listed here.
      </description>
      <schema.changes schema_name="geometry_schema">
         <schema.additions>
            <modified.object type="ENTITY" name="above_plane"/>
            <modified.object type="ENTITY" name="b_spline_volume"/>
            <modified.object type="CONSTANT" name="dummy_gri"/>
            <!-- ... -->
         </schema.additions>
         <schema.modifications>
            <modified.object type="ENTITY" name="axis1_placement"/>
            <modified.object type="FUNCTION" name="base_axis"/>
            <!-- ... -->
         </schema.modifications>
      </schema.changes>
      <schema.changes schema_name="topology_schema">
         <!-- ... -->
      </schema.changes>
   </change_edition>
   <change_edition version="3">
      <description>
         Also changes of technical corrigendum 1 to edition 3 are included here
         that
         modified the description of cartesian_transformation_operator, clarified the
         interpretation of angular parameters, changed the REFERENCE FROM
         statements in the geometric model schema.
      </description>
      <schema.changes schema_name="geometry_schema">
         <schema.additions>
            <modified.object type="ENTITY" name="circular_involute"/>
         </schema.additions>
         <schema.modifications>
            <modified.object type="ENTITY" name="associated_surface"/>
            <!-- ... -->
         </schema.modifications>
      </schema.changes>
   </change_edition>
   <!-- ... -->
   <change_edition version="7">
      <schema.changes schema_name="geometry_schema">
         <schema.modifications>
            <modified.object type="ENTITY" name="curve_bounded_surface">
               <description>
WHERE 'WR4' expression changed</description>
            </modified.object>
            <modified.object type="ENTITY" name="locally_refined_spline_curve">
               <description>Add WHERE 'WR3'</description>
            </modified.object>
            <!-- ... -->
         </schema.modifications>
      </schema.changes>
      <schema.changes schema_name="topology_schema">
         <!-- ... -->
         <schema.deletions>
            <modified.object name="measure_schema"
                             type="REFERENCE_FROM"
                             interfaced.items="length_measure"/>
            <modified.object name="edge_with_length" type="ENTITY"/>
         </schema.deletions>
      </schema.changes>
      <schema.changes schema_name="scan_data_3d_shape_model_schema">
         <description>Corrected schema version identifier.</description>
      </schema.changes>
   </change_edition>
</changes>
```

We want to convert this into:
`data/resources/geometry_schema/geometry_schema.changes.yml`

```yaml
---
schema: geometry_schema
change_edition:
- version: 2
  description: Also changes of technical corrigendum 1 of edition 2 are listed here.
  additions:
  - type: ENTITY
    name: above_plane
  - type: ENTITY
    name: b_spline_volume
  - type: CONSTANT
    name: dummy_gri
  modifications:
  - type: ENTITY
    name: axis1_placement
  - type: FUNCTION
    name: base_axis
- version: 3
  description: |
    Also changes of technical corrigendum 1 to edition 3 are included here
    that
    modified the description of cartesian_transformation_operator, clarified the
    interpretation of angular parameters, changed the REFERENCE FROM
    statements in the geometric model schema.
  additions:
  modifications:
# ...
- version: 7
  description:
  modifications:
  - type: ENTITY
    name: curve_bounded_surface
    description: WHERE 'WR4' expression changed
  - type: ENTITY
    name: locally_refined_spline_curve
    description: Add WHERE 'WR3'
  # This item is not intended for geometry_schema but included here to demonstrate syntax
  - type: REFERENCE_FROM
    name: measure_schema
    interfaced_items: length_measure
```

**Comment by TRThurman** [comment]
In modules,the EXPRESS file names are:arm.exp,mim.exp,arm_lf.exp,mim_lf.exp.TomSent from my iPhoneOn Nov 17, 2022, at 10:44 PM, Ronald Tse ***@***.***> wrote:﻿
Inside resource.xml files there are EXPRESS schema changes (history of changes to the EXPRESS schemas included in that document).
The goal is to migrate these schema change information to the directory location of the schema themselves.
The EXPRESS schemas are located according to this file path pattern:

resources/{schema-name}/{schema-name}.exp
modules/{schema-name}/{schema-name}.exp

We want to create a new YAML file that contains the schema changes at:

resources/{schema-name}/changes.yml
modules/{schema-name}/changes.yml

This is an example from:
data/resource_docs/geometric_and_topological_representation/resource.xml
The document geometric_and_topological_representation includes several schemas, including geometry_schema.

In the <changes> element, it contains multiple <change_edition> elements. Each element represents an editon of this document.
In each <change_edition> element, it contains the changes of individual schemas (such as geometry_schema).
We need to extract these schema changes "per schema" into the {schema-name}/changes.yml file

<changes>
   <change_edition version="2">
      <description>
         Also changes of technical corrigendum 1 of edition 2 are listed here.
      </description>
      <schema.changes schema_name="geometry_schema">
         <schema.additions>
            <modified.object type="ENTITY" name="above_plane"/>
            <modified.object type="ENTITY" name="b_spline_volume"/>
            <modified.object type="CONSTANT" name="dummy_gri"/>
            
         </schema.additions>
         <schema.modifications>
            <modified.object type="ENTITY" name="axis1_placement"/>
            <modified.object type="FUNCTION" name="base_axis"/>
            
         </schema.modifications>
      </schema.changes>
      <schema.changes schema_name="topology_schema">
         
      </schema.changes>
   </change_edition>
   <change_edition version="3">
      <description>
         Also changes of technical corrigendum 1 to edition 3 are included here
         that
         modified the description of cartesian_transformation_operator, clarified the
         interpretation of angular parameters, changed the REFERENCE FROM
         statements in the geometric model schema.
      </description>
      <schema.changes schema_name="geometry_schema">
         <schema.additions>
            <modified.object type="ENTITY" name="circular_involute"/>
         </schema.additions>
         <schema.modifications>
            <modified.object type="ENTITY" name="associated_surface"/>
            
         </schema.modifications>
      </schema.changes>
   </change_edition>
   
   <change_edition version="7">
      <schema.changes schema_name="geometry_schema">
         <schema.modifications>
            <modified.object type="ENTITY" name="curve_bounded_surface">
               <description>
WHERE 'WR4' expression changed</description>
            </modified.object>
            <modified.object type="ENTITY" name="locally_refined_spline_curve">
               <description>Add WHERE 'WR3'</description>
            </modified.object>
            
         </schema.modifications>
      </schema.changes>
      <schema.changes schema_name="topology_schema">
         
         <schema.deletions>
            <modified.object name="measure_schema"
                             type="REFERENCE_FROM"
                             interfaced.items="length_measure"/>
            <modified.object name="edge_with_length" type="ENTITY"/>
         </schema.deletions>
      </schema.changes>
      <schema.changes schema_name="scan_data_3d_shape_model_schema">
         <description>Corrected schema version identifier.</description>
      </schema.changes>
   </change_edition>
</changes>
We want to convert this into:
data/resources/geometry_schema/changes.yml
---
schema: geometry_schema
change_edition:
- version: 2
  description: Also changes of technical corrigendum 1 of edition 2 are listed here.
  additions:
  - type: ENTITY
    name: above_plane
  - type: ENTITY
    name: b_spline_volume
  - type: CONSTANT
    name: dummy_gri
  modifications:
  - type: ENTITY
    name: axis1_placement
  - type: FUNCTION
    name: base_axis
- version: 3
  description: |
    Also changes of technical corrigendum 1 to edition 3 are included here
    that
    modified the description of cartesian_transformation_operator, clarified the
    interpretation of angular parameters, changed the REFERENCE FROM
    statements in the geometric model schema.
  additions:
  modifications:
# ...
- version: 7
  description:
  modifications:
  - type: ENTITY
    name: curve_bounded_surface
    description: WHERE 'WR4' expression changed
  - type: ENTITY
    name: locally_refined_spline_curve
    description: Add WHERE 'WR3'
  # This item is not intended for geometry_schema but included here to demonstrate syntax
  - type: REFERENCE_FROM
    name: measure_schema
    interfaced_items: length_measure

**Comment by HassanAkbar** [comment]
@ronaldtse for `modules` there are some files that includes changes like `mim.changes`, `arm.changes` and `mapping.changes`

```xml
<change version="2">
  <mim.changes>
    <mim.modifications>
      <modified.object name="product_data_equivalence_criteria_schema" type="USE_FROM"/>
    </mim.modifications>
  </mim.changes>
</change>
```

### Questions:

- How should we handle these in the generated `yaml` file?

**Comment by ronaldtse** [comment]
## Module

### With only change for MIM or ARM

For modules, every `module.xml` represents 2 schemas (arm.exp and mim.exp). These schema is named in the `module.name` attribute, appended with the `_arm` or `_mim`.

For example:
* For `data/modules/annotated_3d_model_equivalence_criteria/module.xml`
* The schemas are at:
    * `data/modules/annotated_3d_model_equivalence_criteria/arm.exp` (schema name: Annotated_3d_model_equivalence_criteria_arm)
    * `data/modules/annotated_3d_model_equivalence_criteria/mim.exp` (schema name: Annotated_3d_model_equivalence_criteria_mim)

```
<module xmlns:xlink="http://www.w3.org/1999/xlink"
        name="annotated_3d_model_equivalence_criteria"
         ...
        >
<!-- ... -->
  <changes>
  	<change version="2">
  		<mim.changes>
  			<mim.modifications>
  				<modified.object name="product_data_equivalence_criteria_schema" type="USE_FROM"/>
  			</mim.modifications>
  		</mim.changes>
  	</change>
  </changes>
```

Becomes: `Annotated_3d_model_equivalence_criteria_mim.changes.yml`

```yaml
---
schema: Annotated_3d_model_equivalence_criteria_mim
change_edition:
- version: 2
  description:
  additions:
  - type: USE_FROM
    name: product_data_equivalence_criteria_schema
```

### With only ARM changes

* `data/modules/activity_as_realized/module.xml`
* is about these schemas:
  * `data/modules/activity_as_realized/arm.exp`
  * `data/modules/activity_as_realized/mim.exp`

```xml
<module xmlns:xlink="http://www.w3.org/1999/xlink"
        name="activity_as_realized">
   <!-- ... -->
   <changes>
      <change version="2">
         <description>The ENTITY Activity_happening ARM EXPRESS declarations and interface specifications have been modified.</description>
         <arm.changes>
            <arm.modifications>
               <modified.object name="Activity_happening" type="ENTITY"/>
            </arm.modifications>
         </arm.changes>
      </change>
      <change version="3">
         <description>Updated order of attributes relating_activity and related_activity in Activity_happening.</description>
         <arm.changes>
            <arm.modifications>
               <modified.object name="Activity_happening" type="ENTITY"/>
            </arm.modifications>
         </arm.changes>
      </change>
```

Becomes `data/modules/activity_as_realized/arm.changes.yml`:

```yaml
---
schema: Activity_as_realized_arm
change_edition:
- version: 2
  description: The ENTITY Activity_happening ARM EXPRESS declarations and
    interface specifications have been modified.
  modifications:
  - type: ENTITY
    name: Activity_happening
- version: 3
  description: Updated order of attributes relating_activity and
    related_activity in Activity_happening.
  modifications:
  - type: ENTITY
    name: Activity_happening
```

### With ARM and MIM changes

Then both:
* `data/modules/{module name}/arm.changes.yml`
* `data/modules/{module name}/mim.changes.yml`

Should be created.

## Others

This also means for the resources, we should also use the schema name/path for the yml file.

i.e.
* `data/resources/{schema-name}/{schema-name}.changes.yml`
