### ISSUE TITLE
Failed specs using new Glossarist 2.0 gem

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod-utils#198]
In #196 the Glossarist gem version was updated and the follow specs started failing.

```
Failures:

  1) Stepmod::Utils::TermsExtractor.call returns general_concepts,resource_concepts, parsed_bibliography lists
     Failure/Error: concept.add_l10n(localized_concept)
     
     NoMethodError:
       undefined method `add_l10n' for "16517b9f-2adb-518c-bc7d-7a99293128ae":String
     
               concept.add_l10n(localized_concept)
                      ^^^^^^^^^
     # ./lib/stepmod/utils/terms_extractor.rb:416:in `find_or_initialize_concept'
     # ./lib/stepmod/utils/terms_extractor.rb:302:in `block in parse_annotated_module'
     # ./lib/stepmod/utils/terms_extractor.rb:279:in `each'
     # ./lib/stepmod/utils/terms_extractor.rb:279:in `parse_annotated_module'
     # ./lib/stepmod/utils/terms_extractor.rb:241:in `block in process_term_files'
     # ./lib/stepmod/utils/terms_extractor.rb:198:in `each'
     # ./lib/stepmod/utils/terms_extractor.rb:198:in `process_term_files'
     # ./lib/stepmod/utils/terms_extractor.rb:181:in `call'
     # ./lib/stepmod/utils/terms_extractor.rb:35:in `call'
     # ./spec/stepmod/terms_extractor_spec.rb:6:in `block (2 levels) in <top (required)>'
     # ./spec/stepmod/terms_extractor_spec.rb:48:in `block (3 levels) in <top (required)>'

  2) Stepmod::Utils::TermsExtractor.call For resources/*/descriptions.xml terms takes       only the first paragraph and no additonal tags 
     Failure/Error: concept.add_l10n(localized_concept)
     
     NoMethodError:
       undefined method `add_l10n' for "16517b9f-2adb-518c-bc7d-7a99293128ae":String
     
               concept.add_l10n(localized_concept)
                      ^^^^^^^^^
     # ./lib/stepmod/utils/terms_extractor.rb:416:in `find_or_initialize_concept'
     # ./lib/stepmod/utils/terms_extractor.rb:302:in `block in parse_annotated_module'
     # ./lib/stepmod/utils/terms_extractor.rb:279:in `each'
     # ./lib/stepmod/utils/terms_extractor.rb:279:in `parse_annotated_module'
     # ./lib/stepmod/utils/terms_extractor.rb:241:in `block in process_term_files'
     # ./lib/stepmod/utils/terms_extractor.rb:198:in `each'
     # ./lib/stepmod/utils/terms_extractor.rb:198:in `process_term_files'
     # ./lib/stepmod/utils/terms_extractor.rb:181:in `call'
     # ./lib/stepmod/utils/terms_extractor.rb:35:in `call'
     # ./spec/stepmod/terms_extractor_spec.rb:6:in `block (2 levels) in <top (required)>'
     # ./spec/stepmod/terms_extractor_spec.rb:57:in `block (3 levels) in <top (required)>'

  3) Stepmod::Utils::TermsExtractor.call For modules/*/aim_descriptions.xml terms takes only the first       paragraph and no additonal tags 
     Failure/Error: concept.add_l10n(localized_concept)
     
     NoMethodError:
       undefined method `add_l10n' for "16517b9f-2adb-518c-bc7d-7a99293128ae":String
     
               concept.add_l10n(localized_concept)
                      ^^^^^^^^^
     # ./lib/stepmod/utils/terms_extractor.rb:416:in `find_or_initialize_concept'
     # ./lib/stepmod/utils/terms_extractor.rb:302:in `block in parse_annotated_module'
     # ./lib/stepmod/utils/terms_extractor.rb:279:in `each'
     # ./lib/stepmod/utils/terms_extractor.rb:279:in `parse_annotated_module'
     # ./lib/stepmod/utils/terms_extractor.rb:241:in `block in process_term_files'
     # ./lib/stepmod/utils/terms_extractor.rb:198:in `each'
     # ./lib/stepmod/utils/terms_extractor.rb:198:in `process_term_files'
     # ./lib/stepmod/utils/terms_extractor.rb:181:in `call'
     # ./lib/stepmod/utils/terms_extractor.rb:35:in `call'
     # ./spec/stepmod/terms_extractor_spec.rb:6:in `block (2 levels) in <top (required)>'
     # ./spec/stepmod/terms_extractor_spec.rb:84:in `block (3 levels) in <top (required)>'

  4) Stepmod::Utils::TermsExtractor.call does not include redundant notes
     Failure/Error: concept.add_l10n(localized_concept)
     
     NoMethodError:
       undefined method `add_l10n' for "16517b9f-2adb-518c-bc7d-7a99293128ae":String
     
               concept.add_l10n(localized_concept)
                      ^^^^^^^^^
     # ./lib/stepmod/utils/terms_extractor.rb:416:in `find_or_initialize_concept'
     # ./lib/stepmod/utils/terms_extractor.rb:302:in `block in parse_annotated_module'
     # ./lib/stepmod/utils/terms_extractor.rb:279:in `each'
     # ./lib/stepmod/utils/terms_extractor.rb:279:in `parse_annotated_module'
     # ./lib/stepmod/utils/terms_extractor.rb:241:in `block in process_term_files'
     # ./lib/stepmod/utils/terms_extractor.rb:198:in `each'
     # ./lib/stepmod/utils/terms_extractor.rb:198:in `process_term_files'
     # ./lib/stepmod/utils/terms_extractor.rb:181:in `call'
     # ./lib/stepmod/utils/terms_extractor.rb:35:in `call'
     # ./spec/stepmod/terms_extractor_spec.rb:6:in `block (2 levels) in <top (required)>'
     # ./spec/stepmod/terms_extractor_spec.rb:104:in `block (3 levels) in <top (required)>'

  5) Stepmod::Utils::TermsExtractor.call For modules/*/mim_descriptions.xml terms takes only the first       paragraph and no additonal tags 
     Failure/Error: concept.add_l10n(localized_concept)
     
     NoMethodError:
       undefined method `add_l10n' for "16517b9f-2adb-518c-bc7d-7a99293128ae":String
     
               concept.add_l10n(localized_concept)
                      ^^^^^^^^^
     # ./lib/stepmod/utils/terms_extractor.rb:416:in `find_or_initialize_concept'
     # ./lib/stepmod/utils/terms_extractor.rb:302:in `block in parse_annotated_module'
     # ./lib/stepmod/utils/terms_extractor.rb:279:in `each'
     # ./lib/stepmod/utils/terms_extractor.rb:279:in `parse_annotated_module'
     # ./lib/stepmod/utils/terms_extractor.rb:241:in `block in process_term_files'
     # ./lib/stepmod/utils/terms_extractor.rb:198:in `each'
     # ./lib/stepmod/utils/terms_extractor.rb:198:in `process_term_files'
     # ./lib/stepmod/utils/terms_extractor.rb:181:in `call'
     # ./lib/stepmod/utils/terms_extractor.rb:35:in `call'
     # ./spec/stepmod/terms_extractor_spec.rb:6:in `block (2 levels) in <top (required)>'
     # ./spec/stepmod/terms_extractor_spec.rb:119:in `block (3 levels) in <top (required)>'

Finished in 1.85 seconds (files took 0.62961 seconds to load)
88 examples, 5 failures
```
