### ISSUE TITLE
Schema changes YAML should use String keys

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod-utils#263]
When I ran the annotate command, the generated Changes YAML use symbols instead of strings. I am using the latest version of stepmod-utils.

```yaml
---
schema: aic_machining_feature
change_edition:
- version: '2'
  additions:
  - :type: ENTITY
    :name: gear
  - :type: ENTITY
    :name: thread_runout
  modifications:
  - :type: ENTITY
    :name: chamfer
  - :type: ENTITY
    :name: edge_round
  - :type: ENTITY
    :name: externally_defined_feature_definition
```

<img width="349" alt="image" src="https://github.com/user-attachments/assets/26ecc869-ed8c-47ab-8d86-0d3737f2109f">
